import {
  Flame,
  Trophy,
  Star,
  Medal,
  Award,
  Crown,
  Rocket,
  BookOpen,
  GraduationCap,
  PenTool,
  MessageCircle,
  MessagesSquare,
  Bookmark,
  Heart,
  ThumbsUp,
  Zap,
  Target,
  Compass,
  Sparkles,
  Gem,
  ShieldCheck,
  Sunrise,
} from 'lucide-react-native';

export const BADGE_ICONS: Record<string, typeof Award> = {
  flame: Flame,
  trophy: Trophy,
  star: Star,
  medal: Medal,
  award: Award,
  crown: Crown,
  rocket: Rocket,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  'pen-tool': PenTool,
  'message-circle': MessageCircle,
  'messages-square': MessagesSquare,
  bookmark: Bookmark,
  heart: Heart,
  'thumbs-up': ThumbsUp,
  zap: Zap,
  target: Target,
  compass: Compass,
  sparkles: Sparkles,
  gem: Gem,
  'shield-check': ShieldCheck,
  sunrise: Sunrise,
};
